name: CI/CD for Angular App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List contents of dist directory
        run: |
          echo "Listing the contents of the dist folder:"
          ls -alh ./

      - name: Install dependencies
        run: |
            cd Praneeth_Chand_Portfolio
            npm install    

      - name: Build the Angular project
        run: |
            cd Praneeth_Chand_Portfolio 
            npm run build -- --configuration production

      - name: Install angular-cli-ghpages
        run: |
            cd Praneeth_Chand_Portfolio 
            npm install -g angular-cli-ghpages

      - name: Configure Git user
        run: |
          git config --global user.email "praneethchand99@gmail.com "
          git config --global user.name "PraneethChandG"

      - name: List contents of dist directory
        run: |
          echo "Listing the contents of the dist folder:"
          ls -alh ./Praneeth_Chand_Portfolio/dist


      - name: Set permissions for dist folder
        run: |
          echo ${{ secrets.GH_TOKEN }}
          chmod -R 777 ./Praneeth_Chand_Portfolio/dist/praneeth-chand-portfolio

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=./dist/praneeth-chand-portfolio/browser --repo=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/PraneethChandG/Praneeth_Chand_Portfolio.git --branch=gh-pages --no-silent
          
