name: CI/CD for Angular App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Praneeth_Chand_Portfolio
          npm install

      - name: Build the Angular project
        run: |
          cd Praneeth_Chand_Portfolio
          npm run build -- --configuration production --base-href=/Praneeth_Chand_Portfolio/

      - name: Install angular-cli-ghpages
        run: |
          cd Praneeth_Chand_Portfolio
          npm install -g angular-cli-ghpages

      - name: Deploy to GitHub Pages
        run: |
          cd Praneeth_Chand_Portfolio
          npx angular-cli-ghpages \
            --dir=dist/praneeth-chand-portfolio/browser \
            --repo=https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/PraneethChandG/Praneeth_Chand_Portfolio.git \
            --branch=gh-pages \
            --no-silent
